#!/usr/bin/env python3
"""Export Cloak browser cookies into Agent-Reach channel cookie files."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


CHANNEL_SPECS: dict[str, dict[str, Any]] = {
    "twitter": {
        "domains": [".x.com", ".twitter.com"],
        "required": ["auth_token", "ct0"],
    },
    "reddit": {
        "domains": [".reddit.com", "reddit.com", ".redd.it"],
        "required": [],
    },
    "youtube": {
        "domains": [".youtube.com", "youtube.com", ".google.com"],
        "required": [],
    },
    "xiaohongshu": {
        "domains": [".xiaohongshu.com", "xiaohongshu.com"],
        "required": [],
    },
    "bilibili": {
        "domains": [".bilibili.com", "bilibili.com"],
        "required": ["SESSDATA"],
    },
    "xueqiu": {
        "domains": [".xueqiu.com", "xueqiu.com"],
        "required": ["xq_a_token"],
    },
}


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _default_cookie_dir() -> Path:
    raw = os.environ.get("AGENT_REACH_COOKIE_DIR")
    if raw:
        return Path(raw).expanduser()
    return Path.home() / ".config" / "agent-reach" / "cookies"


def _latest_cloak_export() -> Path | None:
    vault_root = Path(os.environ.get("HERMES_VAULT_PATH", "~/HermesVault")).expanduser()
    cookie_dir = vault_root / "Sessions" / "cookies"
    if not cookie_dir.is_dir():
        return None
    candidates = sorted(
        (p for p in cookie_dir.glob("*.json") if p.is_file()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def _load_json_cookies(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if isinstance(payload, dict):
        cookies = payload.get("cookies")
        if cookies is None and isinstance(payload.get("result"), dict):
            cookies = payload["result"].get("cookies")
    else:
        cookies = payload
    if not isinstance(cookies, list):
        raise ValueError(f"{path} must contain a cookie list or an object with cookies")
    return [_normalise_cookie(cookie) for cookie in cookies if isinstance(cookie, dict)]


async def _load_cdp_cookies() -> list[dict[str, Any]]:
    sys.path.insert(0, str(_repo_root()))
    from tools.cloak._cdp_client import cdp_call

    result = await cdp_call("Network.getAllCookies")
    cookies = result.get("cookies", [])
    if not isinstance(cookies, list):
        return []
    return [_normalise_cookie(cookie) for cookie in cookies if isinstance(cookie, dict)]


def _normalise_cookie(cookie: dict[str, Any]) -> dict[str, Any]:
    normalised = dict(cookie)
    if "expirationDate" in normalised and "expires" not in normalised:
        normalised["expires"] = normalised["expirationDate"]
    normalised.setdefault("path", "/")
    normalised.setdefault("secure", False)
    normalised.setdefault("httpOnly", False)
    return normalised


def _domain_matches(cookie: dict[str, Any], domains: list[str]) -> bool:
    actual = str(cookie.get("domain") or "").lstrip(".").lower()
    if not actual:
        return False
    for domain in domains:
        wanted = domain.lstrip(".").lower()
        if actual == wanted or actual.endswith("." + wanted):
            return True
    return False


def _cookie_header(cookies: list[dict[str, Any]]) -> str:
    pairs = []
    seen = set()
    for cookie in cookies:
        name = str(cookie.get("name") or "")
        value = str(cookie.get("value") or "")
        if not name or name in seen:
            continue
        seen.add(name)
        pairs.append(f"{name}={value}")
    return "; ".join(pairs)


def _netscape_bool(value: Any) -> str:
    return "TRUE" if bool(value) else "FALSE"


def _cookie_expires(cookie: dict[str, Any]) -> int:
    raw = cookie.get("expires", cookie.get("expirationDate", 0))
    try:
        return max(0, int(float(raw)))
    except (TypeError, ValueError):
        return 0


def _netscape_cookie_file(cookies: list[dict[str, Any]]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by Hermes cloak-cookie-bridge.py"]
    for cookie in cookies:
        domain = str(cookie.get("domain") or "")
        if not domain:
            continue
        include_subdomains = domain.startswith(".")
        path = str(cookie.get("path") or "/")
        secure = _netscape_bool(cookie.get("secure"))
        expires = _cookie_expires(cookie)
        name = str(cookie.get("name") or "")
        value = str(cookie.get("value") or "")
        if not name:
            continue
        lines.append(
            "\t".join(
                [
                    domain,
                    _netscape_bool(include_subdomains),
                    path,
                    secure,
                    str(expires),
                    name,
                    value,
                ]
            )
        )
    return "\n".join(lines) + "\n"


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def _write_channel(
    channel: str,
    cookies: list[dict[str, Any]],
    output_dir: Path,
    profile: str,
    exported_at: str,
) -> dict[str, Any]:
    header = _cookie_header(cookies)
    payload = {
        "channel": channel,
        "profile": profile,
        "exported_at": exported_at,
        "cookie_header": header,
        "cookies": cookies,
    }
    json_path = output_dir / f"{channel}.json"
    header_path = output_dir / f"{channel}.txt"
    netscape_path = output_dir / f"{channel}.netscape.txt"

    _write_text(json_path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    _write_text(header_path, header + "\n")
    _write_text(netscape_path, _netscape_cookie_file(cookies))

    required = CHANNEL_SPECS[channel].get("required", [])
    present = {str(cookie.get("name") or "") for cookie in cookies}
    missing = [name for name in required if name not in present]
    return {
        "channel": channel,
        "count": len(cookies),
        "missing_required": missing,
        "files": {
            "json": str(json_path),
            "header": str(header_path),
            "netscape": str(netscape_path),
        },
    }


def bridge_cookies(
    cookies: list[dict[str, Any]],
    output_dir: Path,
    profile: str = "default",
    channels: list[str] | None = None,
) -> dict[str, Any]:
    exported_at = _utc_stamp()
    output_dir.mkdir(parents=True, exist_ok=True)
    selected = channels or list(CHANNEL_SPECS)

    results = []
    for channel in selected:
        spec = CHANNEL_SPECS[channel]
        channel_cookies = [
            cookie for cookie in cookies if _domain_matches(cookie, spec["domains"])
        ]
        results.append(_write_channel(channel, channel_cookies, output_dir, profile, exported_at))

    summary = {
        "ok": True,
        "profile": profile,
        "exported_at": exported_at,
        "output_dir": str(output_dir),
        "channels": results,
    }
    _write_text(output_dir / "summary.json", json.dumps(summary, ensure_ascii=False, indent=2) + "\n")
    return summary


def _load_source(args: argparse.Namespace) -> tuple[list[dict[str, Any]], str]:
    if args.input:
        path = Path(args.input).expanduser()
        return _load_json_cookies(path), str(path)

    if args.source in {"auto", "cdp"}:
        try:
            return asyncio.run(_load_cdp_cookies()), "cdp"
        except Exception:
            if args.source == "cdp":
                raise

    latest = _latest_cloak_export()
    if latest:
        return _load_json_cookies(latest), str(latest)
    raise FileNotFoundError("no Cloak cookie source found")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", help="Path to a Cloak cookie JSON export.")
    parser.add_argument("--source", choices=["auto", "cdp", "latest"], default="auto")
    parser.add_argument("--output-dir", default=str(_default_cookie_dir()))
    parser.add_argument("--profile", default=os.environ.get("HERMES_CLOAK_PROFILE", "default"))
    parser.add_argument(
        "--channel",
        action="append",
        choices=sorted(CHANNEL_SPECS),
        help="Limit export to a channel. May be repeated.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    cookies, source = _load_source(args)
    summary = bridge_cookies(
        cookies=cookies,
        output_dir=Path(args.output_dir).expanduser(),
        profile=args.profile,
        channels=args.channel,
    )
    summary["source"] = source
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
